pipeline {
    agent any
    stages {
        stage('Clonar repositorio') {
            steps {
                git 'https://github.com/usuario/repositorio.git'
            }
        }
        stage('Configurar entorno') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }
        stage('Ejecutar pruebas') {
            steps {
                sh 'python manage.py test'
            }
        }
        stage('Desplegar aplicación') {
            steps {
                sh 'python manage.py migrate'
                sh 'python manage.py collectstatic --noinput'
                sh 'sudo systemctl restart gunicorn'
            }
        }
    }
}
